/**
 * CDS ZF-Cycle — Improvement Pipeline Types
 *
 * The ZF-Cycle is the mechanical improvement loop:
 *   Finding → SCAN (Haiku) → REVIEW (Sonnet) → HOLISTIC (Opus, triggered)
 *   → INJECT (Sonnet) → Gate target updated → Enforcement score rises
 *
 * PREVENTION IS TOP PRIORITY. Every cycle ends with an injection
 * that hardens the insight into at least one gate target.
 */

// =============================================================================
// ZF-CYCLE PIPELINE TYPES
// =============================================================================

export type ZFCyclePhase =
  | 'SCAN'       // Phase 1 — Haiku: pattern scan, severity confirm, related findings
  | 'REVIEW'     // Phase 2 — Sonnet: root cause, options, recommended fix, prevention hook
  | 'HOLISTIC'   // Phase 3 — Opus: cross-finding synthesis (TRIGGERED ONLY)
  | 'INJECT';    // Phase 4 — Sonnet: distill + inject into gate targets

export type ZFCycleStatus =
  | 'PENDING'             // Cycle registered, Phase 1 not yet run
  | 'SCAN_COMPLETE'       // Phase 1 done, ready for Phase 2
  | 'REVIEW_COMPLETE'     // Phase 2 done, ready for Phase 3 or 4
  | 'HOLISTIC_COMPLETE'   // Phase 3 done (if triggered), ready for Phase 4
  | 'INJECTED'            // Phase 4 done — insight in gate targets
  | 'PARKED';             // Cycle paused — needs Governor decision

export type ZFTrigger =
  | 'MANUAL'              // Governor explicitly triggered this cycle
  | 'AUTO_CRITICAL'       // Auto-triggered: finding is CRITICAL severity
  | 'AUTO_BATCH'          // Auto-triggered: 3+ CRITICAL in same domain this week
  | 'SCHEDULED';          // Triggered by weekly session generator

export interface ZFStage {
  phase: ZFCyclePhase;
  model: 'haiku' | 'sonnet' | 'opus';
  status: 'PENDING' | 'COMPLETE' | 'SKIPPED';
  triggered_at?: string;        // ISO8601
  completed_at?: string;        // ISO8601
  // Structured prompt generated by engine for this phase
  prompt: string;
  // Output from model execution (stored after Governor runs the prompt)
  output?: ZFStageOutput;
}

export interface ZFStageOutput {
  // Phase 1 (SCAN) output
  scan_summary?: {
    pattern: string;
    severity_confirmed: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
    related_findings: string[];           // Other finding IDs in the same category
    risk_context: string;
    platform_impact: string;
  };
  // Phase 2 (REVIEW) output
  review_result?: {
    root_cause: string;
    options: Array<{
      approach: string;
      tradeoffs: string;
      effort: 'LOW' | 'MEDIUM' | 'HIGH';
    }>;
    recommended_fix: string;
    prevention_hook: string;              // What to inject into gate targets
    enforcement_after_fix: 'MECHANICAL' | 'CONVENTION';
  };
  // Phase 3 (HOLISTIC) output — only if triggered
  holistic_insight?: {
    platform_pattern: string;            // The systemic pattern across multiple findings
    systemic_risk: string;
    architectural_recommendation: string;
    enforcement_score_delta: number;     // Expected % improvement
  };
  // Phase 4 (INJECT) output
  injection_result?: {
    injection_rule: string;
    targets_updated: string[];
    enforcement_before: 'MECHANICAL' | 'CONVENTION' | 'STUB';
    enforcement_after: 'MECHANICAL' | 'CONVENTION' | 'STUB';
  };
  // Free-form output (fallback if structured not parseable)
  raw_output?: string;
}

export interface ZFCycle {
  zf_id: string;                          // ZFC-YYMMDD-NNN
  finding_id: string;                     // FINDING-[EXPERT]-[SEQ] from audit report
  finding_source: string;                 // e.g. "AUDIT-260702-001"
  trigger: ZFTrigger;
  status: ZFCycleStatus;
  current_phase: ZFCyclePhase;
  created_at: string;                     // ISO8601
  completed_at?: string;                  // ISO8601 — when INJECTED
  governor_parked?: boolean;
  park_reason?: string;
  stages: ZFStage[];
  injection_ids: string[];                // INJ-YYMMDD-NNN IDs from Phase 4
  holistic_triggered: boolean;
  holistic_trigger_reason?: string;
  // The finding being processed (copied from audit report)
  finding: {
    id: string;
    expert: string;
    severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
    title: string;
    detail: string;
  };
}

// =============================================================================
// INJECTION TYPES
// =============================================================================

export interface InjectionTarget {
  id: string;                             // e.g. "GATE-AUTH"
  label: string;
  file: string;                           // Relative path from threshold/
  type: 'creation_gate' | 'impl_milestone' | 'post_impl_check' | 'prevention' | 'audit_evolution';
  phase: string;
  description: string;
  injected_rules: InjectedRule[];
}

export interface InjectedRule {
  rule_id: string;                        // e.g. "P1-AUTH-FIRST"
  source_finding: string;                 // e.g. "FINDING-SEC-002"
  injected_at: string;                    // ISO8601
  rule: string;                           // The prevention rule statement
  enforcement: string;
}

export interface InjectionRecord {
  inj_id: string;                         // INJ-YYMMDD-NNN
  zf_cycle_id: string;                    // ZFC that produced this injection
  finding_id: string;
  insight: string;                        // The distilled insight (1-2 sentences)
  injection_rule: string;                 // The rule added to gate targets
  targets_updated: string[];              // Target IDs that received this injection
  injected_at: string;                    // ISO8601
  injected_by: string;                    // 'sonnet-builder' | actor identity
  enforcement_before: string;
  enforcement_after: string;
}

// =============================================================================
// PARK REGISTRY TYPES
// =============================================================================

export interface ParkEntry {
  park_id: string;                        // PARK-[YYMMDD]-[SEQ]
  title: string;
  description: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'CLOSED' | 'DEFERRED';
  is_forced_escalation: boolean;          // RULE-PARK checks this field
  created_at: string;                     // ISO8601
  closed_at?: string;
  session_target: string;                 // When this will be addressed
  finding_ref: string | null;            // Linked finding ID if from audit
  tags: string[];
  cycle_agenda?: string[];               // For session-type park entries
}

export interface ParkRegistry {
  _meta: {
    registry_id: string;
    version: string;
    last_updated: string;
    note: string;
  };
  entries: ParkEntry[];
}

// =============================================================================
// API SHAPES — ZF-Cycle endpoints
// =============================================================================

export interface StartZFCycleRequest {
  finding_id: string;               // Must exist in a local audit report
  finding_source: string;           // Audit report ID (e.g. "AUDIT-260702-001")
  trigger?: ZFTrigger;
}

export interface StartZFCycleResponse {
  ok: boolean;
  zf_id: string;
  status: ZFCycleStatus;
  phase_1_prompt: string;           // Ready-to-use Haiku prompt for Phase 1
  finding: ZFCycle['finding'];
}

export interface AdvanceZFCycleRequest {
  zf_id: string;
  phase_output: ZFStageOutput;      // Output from running the current phase's prompt
  trigger_holistic?: boolean;       // Governor explicitly requests Opus Phase 3
  // NEW (Pocket #2): Auto-trigger context for domain clustering
  finding_domain?: string;          // Domain tag for this finding (e.g., "Corespine", "Security")
  related_findings_in_domain?: number;  // Count of findings with same domain in current batch
}

export interface AdvanceZFCycleResponse {
  ok: boolean;
  zf_id: string;
  previous_phase: ZFCyclePhase;
  new_status: ZFCycleStatus;
  next_phase?: ZFCyclePhase;
  next_prompt?: string;             // Ready-to-use prompt for next phase (if any)
  ready_to_inject?: boolean;        // True when Phase 2 (or 3) is complete
}

export interface InjectInsightRequest {
  zf_id: string;                    // The ZF cycle that produced the insight
  target_ids: string[];             // Which gate targets to update (from injection-targets.json)
  insight: string;                  // The distilled insight to inject
  injection_rule: string;           // The prevention rule to add
}

export interface InjectInsightResponse {
  ok: boolean;
  inj_id: string;
  targets_updated: string[];
  enforcement_before: string;
  enforcement_after: string;
  zf_status_updated_to: ZFCycleStatus;
}
